models:
  - name: users_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
  # Remove the section below, if you don't want to generate a feature table
  - name: users
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      vars:
        - entity_var:
            name: content_watched
            from: inputs/rsIdentifies
            select: array_agg(distinct content_watched)
            description: All content viewed by the user
        - entity_var:
            name: total_episodes_watched
            from: inputs/rsIdentifies
            select: first_value(number ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Number of episodes watched in total
        - entity_var:
            name: total_movies_rented
            from: inputs/rsIdentifies
            select: first_value(movies_rented ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: Number of movies rented
        - entity_var:
            name: premium_trial_status
            from: inputs/rsIdentifies
            select: first_value(premium_trial_status ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: The premium trial status - not_started, ongoing, expired, upgraded
        - entity_var:
            name: churn_prediction_score
            from: inputs/rsIdentifies
            select: first_value(churn_score ignore nulls)
            window:
              order_by:
                - timestamp desc
            description: The churn prediction score based on past activity
        - entity_var:
            name: total_sessions_to_date
            from: models/rsTracksUnionPages
            select: count(distinct context_session_id)
            where: context_session_id is not null
            description: Total individual sessions created till date.
        - entity_var:
            name: first_name
            from: inputs/rsIdentifies
            select: first_value(first_name)
            window:
              order_by:
                - timestamp desc
            where: first_name is not null and first_name!=''
            description: First name of the customer
        - entity_var:
            name: last_name
            from: inputs/rsIdentifies
            select: first_value(last_name)
            window:
              order_by:
                - timestamp desc
            where: last_name is not null and last_name!=''
            description: Last name of the customer
        - entity_var:
            name: recent_user_email
            from: inputs/rsIdentifies
            select: first_value(email)
            window:
              order_by:
                - timestamp desc
            where: email is not null and email!=''
            description: Email associated to the order
      features:
        - content_watched
        - total_episodes_watched
        - total_movies_rented
        - premium_trial_status
        - churn_prediction_score
        - first_name
        - last_name
        - recent_user_email
        - total_sessions_to_date
