models:
  - name: users_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
  # Remove the section below, if you don't want to generate a feature table
  - name: users
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      features:
        - orders_completed
        - items_left_in_cart
        - total_sessions_to_date
        - most_recent_email
        - firstname
        - lastname
        - is_churned
        - percentile_churn_score
        - user_ltv
        - attribution_sources
        - marketing_campaign
        - first_touch_score
        - last_touch_score
        - linear_attr_score
        - markov_attr_score
var_groups:
  - name: user_vars
    entity_key: user
    vars:
      - entity_var:
          name: orders_completed
          from: inputs/rsIdentifies
          select: sum(number::real)
          description: Number of orders_completed watched in total
      - entity_var:
          name: items_left_in_cart
          from: inputs/rsIdentifies
          select: uniform(0, 3, random())
      - entity_var:
          name: user_ltv
          from: inputs/rsIdentifies
          select: first_value(ltv ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: User LTV
      - entity_var:
          name: is_churned
          from: inputs/rsIdentifies
          select: first_value(user_is_churned ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: Current churn status of the user
      - entity_var:
          name: percentile_churn_score
          from: inputs/rsIdentifies
          select: first_value(percentile_churn ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: The churn propensity score 
      - entity_var:
          name: total_sessions_to_date
          from: inputs/rsIdentifies
          select: uniform(1, 100, random())
          description: Total individual sessions since account creation
      - entity_var:
          name: firstname
          from: inputs/rsIdentifies
          select: first_value(first_name ignore nulls)
          window:
            order_by:
              - timestamp desc
          where: first_name is not null and first_name!=''
          description: First name of the customer
      - entity_var:
          name: lastname
          from: inputs/rsIdentifies
          select: first_value(last_name ignore nulls)
          window:
            order_by:
              - timestamp desc
          where: last_name is not null and last_name!=''
          description: Last name of the customer
      - entity_var:
          name: most_recent_email
          from: inputs/rsIdentifies
          select: first_value(email)
          window:
            order_by:
              - timestamp desc
          where: email is not null and email!=''
          description: Email associated to the order
      - entity_var:
          name: attribution_sources
          from: inputs/rsIdentifies
          select: array_agg(array_construct('Google','Facebook','Reddit','Quora','Wikipedia')[ABS(MOD(Random(),5))]::text)
          description: Attribution source in chronological order
      - entity_var:
          name: marketing_campaign
          from: inputs/rsIdentifies
          select: first_value(campaign ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: Campaign that the user was a part of
      - entity_var:
          name: first_touch_score
          from: inputs/rsIdentifies
          select: first_value(first_touch ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: Campaign that the user was a part of
      - entity_var:
          name: last_touch_score
          from: inputs/rsIdentifies
          select: first_value(last_touch ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: Campaign that the user was a part of
      - entity_var:
          name: linear_attr_score
          from: inputs/rsIdentifies
          select: first_value(linear_score ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: Campaign that the user was a part of
      - entity_var:
          name: markov_attr_score
          from: inputs/rsIdentifies
          select: first_value(markov_score ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: Campaign that the user was a part of
