models:
  - name: users_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
  # Remove the section below, if you don't want to generate a feature table
  - name: users
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      features:
        - days_active_last_30_days
        - total_jobs_viewed
        - total_jobs_applied
        - total_interviews_completed
        - churn_prediction_score
        - most_recent_email
        - total_sessions_to_date
var_groups:
  - name: user_vars
    entity_key: user
    vars:
      - entity_var:
          name: days_active_last_30_days
          from: inputs/rsIdentifies
          select: uniform(10, 100, random())
          description: The number of days the user has been active in the last 30 days
      - entity_var:
          name: total_jobs_viewed
          from: inputs/rsIdentifies
          select: uniform(50, 100, random())
          description: Number of episodes watched in total
      - entity_var:
          name: total_jobs_applied
          from: inputs/rsIdentifies
          select: uniform(20, 50, random())
          description: Number of movies rented
      - entity_var:
          name: total_interviews_completed
          from: inputs/rsIdentifies
          select: uniform(1, 20, random())
          description: Has the user completed a vikipass trial?
      - entity_var:
          name: churn_prediction_score
          from: inputs/rsIdentifies
          select: first_value(churn_score ignore nulls)
          window:
            order_by:
              - timestamp desc
          description: The churn prediction score based on past activity
      - entity_var:
          name: total_sessions_to_date
          from: models/rsTracksUnionPages
          select: count(distinct context_session_id)
          where: context_session_id is not null
          description: Total individual sessions created till date.
      - entity_var:
          name: most_recent_email
          from: inputs/rsIdentifies
          select: first_value(email)
          window:
            order_by:
              - timestamp desc
          where: email is not null and email!=''
          description: Email associated to the order
